// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"854","screenHeight":"432","changeWindowWidthTo":"854","changeWindowHeightTo":"432","renderingMode":"auto","alwaysDash":"on"}},
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"1232","screenHeight":"624","changeWindowWidthTo":"1232","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"on"}},
{"name":"TouchUI","status":false,"description":"Change the UI for the touch operation.","parameters":{"Menu Command Text":"Menu","Previous Command Text":"<","Next Command Text":">"}},
{"name":"SVActorPosition","status":false,"description":"Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"600","actor1 Ypos":"80","actor2 Xpos":"632","actor2 Ypos":"128","actor3 Xpos":"664","actor3 Ypos":"176","actor4 Xpos":"696","actor4 Ypos":"224"}}
];
