// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_Debugger","status":true,"description":"v2.07 This is Yanfly's debugger plugin tool given to\nfaithful supporters to help you testplay your game better!","parameters":{"---Startup---":"","Auto New Game":"true","Auto Show FPS":"false","Auto Full Screen":"false","Auto Console":"false","---Visual---":"","Debug Window Tone":"50, 50, 50, 0","Console Messages":"true","---Field---":"","Field Debug":"false","Debug Menu Icon":"225","---Battle---":"","Battle Test TP Start":"value = user.maxTp()","Damage CTRL Modifier":"value *= -1","Damage SHIFT Modifier":"value *= 10","EXP CTRL Modifier":"rate *= 100","EXP SHIFT Modifier":"rate *= 10","Warning Message":"true","Disable Variance":"false","100% State Rate":"false","---Spawn Options---":"","Spawn at Boat":"true","Spawn at Ship":"true","Spawn at Airship":"true"}},
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"938","screenHeight":"528","changeWindowWidthTo":"938","changeWindowHeightTo":"528","renderingMode":"auto","alwaysDash":"on"}},
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"1280","changeWindowHeightTo":"720","renderingMode":"auto","alwaysDash":"on"}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"1366","screenHeight":"768","changeWindowWidthTo":"1366","changeWindowHeightTo":"768","renderingMode":"auto","alwaysDash":"on"}},
{"name":"GM_Geral","status":true,"description":"Configurações gerais.","parameters":{}},
{"name":"GM_Battle","status":true,"description":"Configurações da batalha.","parameters":{}},
{"name":"GM_Touch_UI","status":true,"description":"","parameters":{}},
{"name":"GM_Battle_FV","status":true,"description":"Batalha front view.","parameters":{}},
{"name":"SVActorPosition","status":false,"description":"Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"306","actor1 Ypos":"527","actor2 Xpos":"469","actor2 Ypos":"527","actor3 Xpos":"632","actor3 Ypos":"527","actor4 Xpos":"770","actor4 Ypos":"345"}},
{"name":"SVActorPosition","status":true,"description":"Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"448","actor1 Ypos":"767","actor2 Xpos":"754","actor2 Ypos":"767","actor3 Xpos":"1058","actor3 Ypos":"767","actor4 Xpos":"770","actor4 Ypos":"345"}},
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"1","position":"1"}},
{"name":"BattleVoice","status":true,"description":"play voice SE at battle when actor does spcified action","parameters":{"pitch":"100","volume":"100"}},
{"name":"HPConsumeSkill_(Edit)","status":true,"description":"make the skill that consumes HP, not only MP and/or TP","parameters":{}},
{"name":"TDDP_PixelPerfect","status":true,"description":"1.1.1 Enable pixel perfect scaling mode for your game","parameters":{"enableIngameOptions":"true","labels":"","en":"Pixel Perfect Mode","ja":"ピクセルパーフェクトモード","zh":"像素完美模式","ko":"픽셀 퍼펙트 모드","ru":"Режим Pixel Perfect"}},
{"name":"---[SV Plugins]---","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"SVActorPosition","status":false,"description":"Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"640","actor1 Ypos":"180","actor2 Xpos":"672","actor2 Ypos":"228","actor3 Xpos":"704","actor3 Ypos":"276","actor4 Xpos":"736","actor4 Ypos":"324"}},
{"name":"MOG_ActorPictureCM","status":false,"description":"(v2.4 *) Apresenta a imagem do personagem durante a seleção de comandos.","parameters":{"-> MAIN <<<<<<<<<<<<<<<<<<<<<<<":"","Slide Speed":"10","File Name":"Actor_","":"","-> BUST <<<<<<<<<<<<<<<<<<<<<<<":"","Bust Visible":"true","Bust X-Axis":"0","Bust Y-Axis":"-180","Bust Slide X":"-150","Bust Slide Y":"0","Breath Effect":"false","Blink Effect":"false","Blink Speed":"7","Blinking Interval":"190","-> FACE <<<<<<<<<<<<<<<<<<<<<<<":"","Face Visible":"false","Face X-Axis":"570","Face Y-Axis":"0","Face Slide X":"150","Face Slide Y":"0"}}
];
